name: ui_kit
description: A package for building user interfaces in Flutter.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  # For generating random numbers and data
