name: local_storage
description: A package for local data storage with swappable implementations.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  convert: ^3.1.1
